apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: interior-interconnect
spec:
  # Add fields here
  deploymentPlan:
    role: interior
    size: 3
    placement: Any
